Document: keysight-n5171b
Title: Debian keysight-n5171b Manual
Author: <insert document author here>
Abstract: This manual describes what keysight-n5171b is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/keysight-n5171b/keysight-n5171b.sgml.gz

Format: postscript
Files: /usr/share/doc/keysight-n5171b/keysight-n5171b.ps.gz

Format: text
Files: /usr/share/doc/keysight-n5171b/keysight-n5171b.text.gz

Format: HTML
Index: /usr/share/doc/keysight-n5171b/html/index.html
Files: /usr/share/doc/keysight-n5171b/html/*.html
